### ISSUE TITLE
不错哦，收集这么多

### ISSUE THREAD

**Issue by LiliCode** [WangGuibin/WGBToolsConfigRepository#1]
最近怎么没上线了。

**Comment by WangGuibin** [comment]
@LiliCode 邮件回了,为啥不会出现在这了...   我那个号没了,加这个
![t_me-CoderWGB](https://github.com/WangGuibin/WGBToolsConfigRepository/assets/15259130/62520dbd-8c09-411c-9e9c-8f9541586eef)
